apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data: #for backend we need db server host
  DB_HOST: mysql # mysql component service name, now we need to refer this configmap in pod
  #DB_HOST: db-dev.csvdaws78s.online

----
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-dev.daws78s.online; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: ravidaws/backend:v1.0
        
        envFrom:
        - configMapRef:  # refering from configmap top
            name: backend


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port